[package]
name = "rocket_sample_data"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.3"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"

[dev-dependencies]
tokio = "1"
mockito = "0.3"
serde_json = "1"
